"""Planar circular restricted three-body problem (Sun + Jupiter + test particles).

Units: AU and years. Choice of units makes G * M_sun = 4*pi^2, so a body
on a 1 AU circular orbit has period 1 yr (Kepler's third law).

Jupiter is held on a fixed circular orbit of radius `a_J`; test particles
are massless and evolve under the Sun and Jupiter gravity only. This is
the standard setting in which Wisdom (1982) demonstrated that the 3:1
Kirkwood gap is generated by chaotic orbital dynamics.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

MU_SUN = 4.0 * np.pi ** 2          # AU^3 / yr^2
JUP_MASS_RATIO = 9.5458e-4         # m_J / m_sun
MU_JUP = MU_SUN * JUP_MASS_RATIO
A_JUP = 5.2028                     # AU
T_JUP = A_JUP ** 1.5               # yr (Kepler 3rd)
N_JUP = 2.0 * np.pi / T_JUP        # mean motion, rad/yr


@dataclass(frozen=True)
class KirkwoodParams:
    mu_sun: float = MU_SUN
    mu_jup: float = MU_JUP
    a_jup: float = A_JUP
    n_jup: float = N_JUP


def jupiter_position(t: float, p: KirkwoodParams) -> tuple[float, float]:
    angle = p.n_jup * t
    return p.a_jup * np.cos(angle), p.a_jup * np.sin(angle)


def accelerations(
    t: float,
    x: np.ndarray,
    y: np.ndarray,
    p: KirkwoodParams,
) -> tuple[np.ndarray, np.ndarray]:
    """Return (ax, ay) for each test particle position (x, y)."""
    r2_sun = x * x + y * y
    inv_r3_sun = r2_sun ** -1.5

    xj, yj = jupiter_position(t, p)
    dx = x - xj
    dy = y - yj
    r2_jup = dx * dx + dy * dy
    inv_r3_jup = r2_jup ** -1.5

    ax = -p.mu_sun * x * inv_r3_sun - p.mu_jup * dx * inv_r3_jup
    ay = -p.mu_sun * y * inv_r3_sun - p.mu_jup * dy * inv_r3_jup
    return ax, ay


def rk4_step(
    t: float,
    x: np.ndarray,
    y: np.ndarray,
    vx: np.ndarray,
    vy: np.ndarray,
    dt: float,
    p: KirkwoodParams,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Vectorized RK4 step for N test particles in the CR3BP."""
    ax1, ay1 = accelerations(t, x, y, p)
    kx1, ky1 = vx, vy

    x2 = x + 0.5 * dt * kx1
    y2 = y + 0.5 * dt * ky1
    vx2 = vx + 0.5 * dt * ax1
    vy2 = vy + 0.5 * dt * ay1
    ax2, ay2 = accelerations(t + 0.5 * dt, x2, y2, p)
    kx2, ky2 = vx2, vy2

    x3 = x + 0.5 * dt * kx2
    y3 = y + 0.5 * dt * ky2
    vx3 = vx + 0.5 * dt * ax2
    vy3 = vy + 0.5 * dt * ay2
    ax3, ay3 = accelerations(t + 0.5 * dt, x3, y3, p)
    kx3, ky3 = vx3, vy3

    x4 = x + dt * kx3
    y4 = y + dt * ky3
    vx4 = vx + dt * ax3
    vy4 = vy + dt * ay3
    ax4, ay4 = accelerations(t + dt, x4, y4, p)
    kx4, ky4 = vx4, vy4

    nx = x + (dt / 6.0) * (kx1 + 2.0 * kx2 + 2.0 * kx3 + kx4)
    ny = y + (dt / 6.0) * (ky1 + 2.0 * ky2 + 2.0 * ky3 + ky4)
    nvx = vx + (dt / 6.0) * (ax1 + 2.0 * ax2 + 2.0 * ax3 + ax4)
    nvy = vy + (dt / 6.0) * (ay1 + 2.0 * ay2 + 2.0 * ay3 + ay4)
    return nx, ny, nvx, nvy


def initial_conditions(
    n_particles: int,
    a_min: float,
    a_max: float,
    e: float = 0.05,
    seed: int = 0,
    p: KirkwoodParams = KirkwoodParams(),
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Place `n_particles` test bodies on Kepler orbits at random periapsis angles.

    Each particle starts at perihelion with a uniform random argument of
    periapsis. Returns (a0, x, y, vx, vy).
    """
    rng = np.random.default_rng(seed)
    a0 = rng.uniform(a_min, a_max, size=n_particles)
    omega = rng.uniform(0.0, 2.0 * np.pi, size=n_particles)

    r = a0 * (1.0 - e)
    v = np.sqrt(p.mu_sun * (1.0 + e) / r)

    x = r * np.cos(omega)
    y = r * np.sin(omega)
    vx = -v * np.sin(omega)
    vy = v * np.cos(omega)
    return a0, x, y, vx, vy


def semi_major_axis(
    x: np.ndarray, y: np.ndarray, vx: np.ndarray, vy: np.ndarray,
    p: KirkwoodParams = KirkwoodParams(),
) -> np.ndarray:
    """Instantaneous osculating semi-major axis from vis-viva."""
    r = np.sqrt(x * x + y * y)
    v2 = vx * vx + vy * vy
    denom = 2.0 / r - v2 / p.mu_sun
    with np.errstate(divide="ignore", invalid="ignore"):
        a = np.where(denom > 0, 1.0 / denom, np.nan)
    return a


def resonance_locations(p: KirkwoodParams = KirkwoodParams()) -> dict[str, float]:
    """Semi-major axes (AU) of the main Kirkwood resonances with Jupiter.

    For a p:q mean-motion resonance where the asteroid's period ratio to
    Jupiter's is q/p (asteroid faster), Kepler's third law gives
    a = a_J * (q/p)^(2/3).
    """
    return {
        "3:1": p.a_jup * (1.0 / 3.0) ** (2.0 / 3.0),
        "5:2": p.a_jup * (2.0 / 5.0) ** (2.0 / 3.0),
        "7:3": p.a_jup * (3.0 / 7.0) ** (2.0 / 3.0),
        "2:1": p.a_jup * (1.0 / 2.0) ** (2.0 / 3.0),
    }
